### PR TITLE
fix: Name bug

### LINKED ISSUE #29: fix : `Name` bug
## TL/DR

Currently if you search using the capitalized version of a Pokemon's name no results are returned. If you change the name to lowercase everything works. 

Image

_Screen capture, `Name` bug_

Any solution should allow for capitalized and non-capitalized Pokemon names. Valid names should return a result regardless of capitalization. Additionally, if a request fails a message should be served to the user.

### PR DESCRIPTION
**Pull request by mathiuskitchens**
Fixed name bug, also updated `error` span to display error when no result is returned and fixed its positioning

[optional footer(s)]

# Description

<<_Please include a summary of the change._>>

## Type of change

- [x] - fix: - patches a bug in the codebase
- [ ] - feat: - introduces a new feature
- [ ] - build: - relates to build tooling / project scaffolding
- [ ] - chore: - non-code related changes, like adding packages / libraries
- [ ] - docs: - changes related to documentation

## Related Issue

Does this change have a related issue in the project?

- [x] - Yes - Closes #29 
- [ ] - No

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -129,6 +132,6 @@ goButton?.addEventListener('click', (e) => {
   if (inputElement.value === '') {
     errorSpan.innerHTML = 'Please enter a Pokemon Name or ID';
   } else {
-    getPokemon(inputElement.value);
+    getPokemon(inputElement.value.toLowerCase());
```
Comment (wijohnst) [inline src/index.js]: Very nice! 

This is a pretty standard form of validation for text inputs and always worth considering. 

Another that comes to mind is removing white space from before and after the input. 

So like:

What happens when someone enters:

" Pikachu"

It has leading white space. Will your app still work?

**Review by wijohnst — APPROVED** [review]
Looks good!

File: src/index.js (hunk 1 above)
Comment (mathiuskitchens) [reply src/index.js]: Great point, added a fix for that scenario

**Review by wijohnst — APPROVED** [review]
